translate_dict = {
    'accumulated_hectares': {'en': 'Accumulated hectares', 'es': 'Hectáreas acumuladas', 'pt': 'Hectares acumulados'}, 
    'area': {'en': 'Area', 'es': 'Área', 'pt': 'Área'}, 
    'choose_option': {'en': 'Choose an option', 'es': 'Elije una opción', 'pt': 'Escolha uma opção'}, 
    'color_palette': {'en': 'Color Palette', 'es': 'Paleta de colores', 'pt': 'Paleta de Cores'}, 
    'crop': {'en': 'Crop', 'es': 'Cultivo', 'pt': 'Cultura'}, 
    'crops': {'en': 'Crops', 'es': 'Cultivos', 'pt': 'Culturas'}, 
    'dashboards': {'en': 'Dashboards', 'es': 'Tableros', 'pt': 'Painéis'},
    'dem_interval': {'en': 'Interval between contour lines (m)', 'es': 'Intervalo entre curvas de nivel (m)', 'pt': 'Intervalo entre curvas de nível (m)'},
    'download_csv': {'en': 'Download CSV', 'es': 'Descargar CSV', 'pt': 'Baixar CSV'}, 
    'download_geojsons': {'en': 'Download GeoJSON Files', 'es': 'Descargar archivos GeoJSON', 'pt': 'Baixar Arquivos GeoJSON'},
    'download_geojson': {'en': 'Download GeoJSON File', 'es': 'Descargar archivo GeoJSON', 'pt': 'Baixar Arquivo GeoJSON'},
    'domain': {'en': 'Domain', 'es': 'Dominio', 'pt': 'Domínio'},
    'error_message_date_picker': {'en': 'Select start and end date', 'es': 'Seleccione una fecha de inicio y fin', 'pt': 'Selecione uma data de início e término'}, 
    'exclude': {'en': 'Exclude', 'es': 'Excluir', 'pt': 'Excluir'}, 
    'experimental_preview': {'en': 'Experimental Preview', 'es': 'Vista Previa Experimental', 'pt': 'Pré-visualização Experimental'},
    'farm': {'en': 'Farm', 'es': 'Establecimiento', 'pt': 'Fazenda'}, 
    'farms': {'en': 'Farms', 'es': 'Establecimientos', 'pt': 'Fazendas'}, 
    'field': {'en': 'Field', 'es': 'Lote', 'pt': 'Lote'}, 
    'fields': {'en': 'Fields', 'es': 'Lotes', 'pt': 'Lotes'}, 
    'fields_without_crops': {'en': 'Fields without crops', 'es': 'Lotes sin cultivos', 'pt': 'Lotes sem cultivos'}, 
    'fields_without_hybrids_or_varieties': {'en': 'Fields without hybrids/varieties', 'es': 'Lotes sin híbridos/variedades', 'pt': 'Lotes sem híbridos/variedades'}, 
    'generate_altimetry_maps': {'en': 'Generate Altimetry Maps', 'es': 'Generar mapas de altimetría', 'pt': 'Gerar Mapas de Altimetria'},
    'fields_without_sowing_date': {'en': 'Fields without sowing date', 'es': 'Lotes sin fecha de siembra', 'pt': 'Lotes sem data de plantio'}, 
    'heatmap': {'en': 'Heatmap by Hectares', 'es': 'Heatmap por Hectáreas', 'pt': 'Heatmap por Hectares'}, 
    'hectares': {'en': 'Hectares', 'es': 'Hectáreas', 'pt': 'Hectares'}, 
    'hectares_by': {'en': 'Hectares by', 'es': 'Hectáreas por', 'pt': 'Hectares por'}, 
    'hectares_per_date': {'en': 'Hectares per seeding date', 'es': 'Hectáreas por fecha de siembra', 'pt': 'Hectares por data de semeadura'}, 
    'hybrid_varieties': {'en': 'Hybrids / Varieties', 'es': 'Híbridos / Variedades', 'pt': 'Híbridos / Variedades'}, 
    'hybrid_variety': {'en': 'Hybrid / Variety', 'es': 'Híbrido / Variedad', 'pt': 'Híbrido / Variedade'}, 
    'include': {'en': 'Include', 'es': 'Incluir', 'pt': 'Incluir'}, 
    'language': {'en': 'Language', 'es': 'Idioma', 'pt': 'Idioma'}, 
    'logout': {'en': 'Logout', 'es': 'Cerrar Sesión', 'pt': 'Sair'}, 
    'map_type_selector': {'en': 'Map type selector', 'es': 'Selector de tipo de mapa', 'pt': 'Seletor de tipo de mapa'}, 
    'metrics': {'en': 'Metrics', 'es': 'Métricas', 'pt': 'Métricas'}, 
    'only_no_date': {'en': 'Only Without Date', 'es': 'Solo Sin Fecha', 'pt': 'Somente Sem Data'}, 
    'points': {'en': 'Points', 'es': 'Puntos', 'pt': 'Pontos'}, 
    'polygons': {'en': 'Polygons', 'es': 'Polígonos', 'pt': 'Polígonos'}, 
    'point_map_by_field_according_to': {'en': 'Map by Field According to', 'es': 'Mapa de lotes según', 'pt': 'Mapa por Campo Segundo'}, 
    'requested_by': {'en': 'Requested by: ', 'es': 'Solicitado por: ', 'pt': 'Solicitado por: '}, 
    'remaining_time': {'en': 'Approximate remaining time: ', 'es': 'Tiempo restante aproximado: ', 'pt': 'Tempo restante aproximado'},
    'season': {'en': 'Season', 'es': 'Campaña', 'pt': 'Safra'}, 
    'seeding_date': {'en': 'Seeding Date', 'es': 'Fecha de siembra', 'pt': 'Data de Semeadura'}, 
    'seeding_date_by': {'en': 'Seeding Date by ', 'es': 'Fecha de siembra por ', 'pt': 'Data de Semeadura por '}, 
    'seeding_progress': {'en': 'Seeding progress', 'es': 'Avance de siembra', 'pt': 'Progresso da semeadura'}, 
    'select_all': {'en': 'Select all', 'es': 'Seleccionar todo', 'pt': 'Selecionar tudo'}, 
    'select_date_range': {'en': 'Select Date Range:', 'es': 'Seleccionar Rango de Fechas:', 'pt': 'Selecionar Intervalo de Datas:'}, 
    'select_grouping_field': {'en': 'Select a grouping field:', 'es': 'Seleccione un campo de agrupamiento:', 'pt': 'Selecione um campo de agrupamento:'}, 
    'select_warning': {'en': 'You must select a field to continue', 'es': 'Debe seleccionar un lote para continuar', 'pt': 'Você deve selecionar um campo para continuar'}, 
    'title': {'en': 'Fields and Crops Dashboard', 'es': 'Tablero de Lotes y Cultivos', 'pt': 'Painel de Campos e Cultivos'}, 
    'title_yield': {"en": "Yield Dashboard", "es": "Tablero de Rindes", "pt": "Painel de Rendimento"}, 
    'ver_mas': {'en': 'see more...', 'es': 'ver más...', 'pt': 'ver mais...'},
    'workspace': {'en': 'Work Space', 'es': 'Espacio de Trabajo', 'pt': 'Espaço de Trabalho'}, 
    'adjusted_average_yield': {'en': 'Adjusted Average Yield', 'es': 'Rendimiento Medio Ajustado', 'pt': 'Rendimento Médio Ajustado'}, 
    'adjusted_average_yield_by': {'en': 'Adjusted Average Yield by', 'es': 'Rendimiento medio ajustado por', 'pt': 'Rendimento Médio Ajustado por'}, 
    'average_yield': {'en': 'Average Yield', 'es': 'Rendimiento Medio', 'pt': 'Rendimento Médio'}, 
    'point_map_by_layer_according_to': {'en': 'Point Map by Layer According to', 'es': 'Mapa de puntos por capa según', 'pt': 'Mapa de Pontos por Camada Segundo'}, 
    'select_yield_layer_warning': {'en': 'You must select a yield layer to continue', 'es': 'Debe seleccionar una capa de rindes para continuar', 'pt': 'Você deve selecionar uma camada de rendimento para continuar'}, 
    'vertical_exaggeration': {'en': 'Vertical exaggeration', 'es': 'Exageración vertical', 'pt': 'Exageração vertical'},
    'weighted_yield': {'en': 'Weighted Yield', 'es': 'Rendimiento Ponderado', 'pt': 'Rendimento Ponderado'}, 
    'weighted_yield_by': {'en': 'Weighted Yield by', 'es': 'Rendimiento Ponderado por', 'pt': 'Rendimento Ponderado por'}, 
    'yield_layer': {'en': 'Yield Layer', 'es': 'Capa de Rinde', 'pt': 'Camada de Rendimento'}, 
    'yield_layers': {'en': 'Yield Layers', 'es': 'Capas de rindes', 'pt': 'Camadas de Rendimento'},
    'proximamente': {'en': 'Coming Soon!', 'es': 'Próximamente!', 'pt': 'Em Breve!'},
    'fields_and_crops_dashboard_description': {'en': 'This dashboard provides a detailed view and analysis of the composition of fields and crops registered in the 360 platform. It also allows for the assessment of planting progress through the analysis of planting date data',
                                               'es': 'Este tablero ofrece una visión detallada y permite el análisis de la composición de lotes y cultivos registrados en la plataforma 360. Además, facilita la evaluación del progreso de la siembra mediante el análisis de los datos correspondientes a las fechas de siembra',
                                               'pt': 'Este painel oferece uma visão detalhada e permite a análise da composição de lotes e culturas registradas na plataforma 360. Além disso, facilita a avaliação do progresso do plantio por meio da análise dos dados de datas de plantio'
                                               },
    'yield_dashboard_description': {'en': '',
                                    'es': '',
                                    'pt': ''
                                    },
    }
